# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  name: ubuntu-pool

jobs:
  - job: TestAgent
    displayName: "Test Self-Hosted Agent"
    steps:
      - script: uname -a
        displayName: "Show OS info"

      - script: whoami
        displayName: "Show current user"

      - script: df -h
        displayName: "Show disk usage"
